version: "2"

linters:
  enable:
    - godoclint
    - godot
    - revive
    - staticcheck

  settings:
    godoclint:
      default: all
      require-doc:
        ignore-unexported: false
      start-with-name:
        include-unexported: true

    godot:
      scope: all
      capital: true

    revive:
      rules:
        - name: package-comments
        - name: exported
          arguments:
            - check-private-receivers
